name: Weekly Upgrade

on:
  schedule:
    - cron: 0 12 * * 3

jobs:
  upgrade:

    runs-on: ubuntu-latest
    
    steps:
    - name: GitHub Action for package.json update.
      uses: taichi/actions-package-update@v0.5.0
